### ISSUE TITLE
Help with your dots

### ISSUE THREAD

**Issue by syylvette** [MCotocel/nixdots#1]
Hello, I reached till final step of installation and logged in as user but I just see the default theme of awesome it doesnot show your rice. Do I need to run any other command after login as user?

**Comment by MCotocel** [comment]
Could you put `awesome >> ~/.cache/awesome/stdout 2>> ~/.cache/awesome/stderr` in your `.xinitrc` and upload the log here?

**Comment by syylvette** [comment]
Can you share your .xinitrc file and also where you need to place it.
I was using sddm by uncommenting the sddm stuff in desktop.nix

**Comment by syylvette** [comment]
> Could you put `awesome >> ~/.cache/awesome/stdout 2>> ~/.cache/awesome/stderr` in your `.xinitrc` and upload the log here?

I created .xinitrc in ~ and added this I am getting the below screen but its stuck ig I cant move my mouse and also keyboard keys not working

![IMG20230219150755](https://user-images.githubusercontent.com/105774228/219940339-66fcb500-cf50-450e-b9fd-3b3ea0bff632.jpg)

**Comment by syylvette** [comment]
stderr
![IMG20230219151831](https://user-images.githubusercontent.com/105774228/219940809-975b3268-c4ef-452f-9bfa-b4232285ae6e.jpg)

**Comment by MCotocel** [comment]
The `sddm` package was commented out for a reason, it doesn't work for me at the moment.

Try commenting out lines 23-27 in the `autostart.sh` file in the `awesome` directory.

**Comment by MCotocel** [comment]
Closed due to inactivity
